rcw.py: Fix indexing with floats
When creating a source PBI from a binary, the following error is
encountered:

> TypeError: slice indices must be integers or None or have an __index__ method

This is because division in python3 always returns a float. Instead, use
the integer division operator, which returns a (truncated) int.

Fixes: 7c47f30 ("Add support of Gen3 family SoCs")
Signed-off-by: Sean Anderson <sean.anderson@seco.com>