Fix RCW binary decoding after python3 conversion
It looks like after the script conversion to python3, it fails in
multiple places.

$ python3 ./rcw.py -i ls1021atsn/SSR_PNS_30/rcw_1200_qspiboot.bin -r --rcwi ls1021aqds/ls1021a.rcwi
Traceback (most recent call last):
  File "./rcw.py", line 1023, in <module>
    f.write(create_source())
  File "./rcw.py", line 858, in create_source
    pbi += "\0\0\0"
TypeError: can't concat str to bytes

Other fixes for byte / string conversions, which were tested with these
commands:

python3 ./rcw.py -i ./ls1043ardb/RR_FQPP_1455/rcw_1400.bin -r --rcwi ./ls1043aqds/ls1043a.rcwi
python3 ./rcw.py -i ./ls1046ardb/RR_FFSSPPPH_1133_5559/rcw_1200_qspiboot.bin -r --rcwi ./ls1046ardb/ls1046a.rcwi

And one more fix when formatting the elements of bitstring object:

Depending on the value of %classicbitnumbers, the RCW bit string can be
either <class 'bytes'> or <class 'string'>.
For each of these object types, we need to transmit a byte type argument
to format function when iterating through the bitstring object. If x is
an element of bitstring then format function will be invoked either as
'format(x)' for byte object or 'format(ord(x))' for string object.

Fixes: 3f744d305cd9 ("Convert to python3")

Signed-off-by: Radu Bulie <radu-andrei.bulie@nxp.com>
Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>