rcw.py: Fix using ord on ints
Iterating over a bytestring will yield integers in python 3, so we don't
need to convert them with ord(). This avoids the following error:

> TypeError: ord() expected string of length 1, but int found

Fixes: 7c47f30 ("Add support of Gen3 family SoCs")
Signed-off-by: Sean Anderson <sean.anderson@seco.com>